### ISSUE TITLE
Model is overestimating

### ISSUE THREAD

**Issue by ppaulojr** [covid19br/covid19br.github.io#7]
Right now the model is grossly overestimating cases. I've been following it for some day and we are well below the minimum predicted to the next day.

If we don't make accurate predictions for D+1 I don't see the point in extrapolating it to five days.

**Comment by tapirus07** [comment]
I have tried hierarchical mixed models to estimate some tendencies. Take a look if you believe it is useful. 

http://movement-wildlife.shinyapps.io/APP-2/

**Comment by vsudbrack** [comment]
I guess being naive at this point would be assuming the data we have now for Brazil represents the dynamics of the disease while press recurrently addresses  issues in testing and analyzing data. We do not believe we've already reached the effects of saturation. Overestimation occurs due to the thousands of tests still waiting to be done. We've published in +Info an analysis of the first 20 days of predictions. 
Best regards!

**Comment by tapirus07** [comment]
Thanks for your considerations Vitor. I appreciates data and code sharing, as well interface of disclosuring. Best!

**Comment by lazaronixon** [comment]
hello, I am using your data set to calculate http://profetadocorona.herokuapp.com and using this model to calculate logistic growth https://github.com/katanaml/covid19

**Comment by tapirus07** [comment]
lazaronixon,

really cool. I did a very similar approach, but it woth to note two important differences.

1. I used a different equation to model logistic growth, beacuse I tried to link biological meaning to each parameter. 
I used : Cases ~ c/1+exp((b-time)/a), so in my formulation some quantities are straighfoward to get: "c" is the asymptote, "b" is time of inflection point, and "a" is the velocity. Note b+3*a is time when we reach 95% of the cases.

2. Because logistic estimation for most countries in exponential growth will be very poor, I ran a unique mixed logistic regression for all countries, including parameters "a", "b" and "c" as random effects. That mean that individual parameter estimations of each country are part of a big populational Gaussian sample with certain estimated mean and variance. Therefore, countries with few initial data would be better estimated by using this shared information.

Anyway, I appreciated a lot your approach and dashboard.

Please, let me know if you have further ideas or inputs. Gustavo.
